Flowpack:
  Authentication:
    Facebook:
      application:
        id: 'IDIDIDIDID'
        secret: 'The secret goes to the grave of the deep blue sea'
        scope: ''
        redirect_uri:
          #'@package': 'Scoutrace.Scoutrace'
          #'@controller': 'Standard'
          #'@action': 'index'
          #'@subpackage': NULL
          '@package': 'Flowpack.Authentication.Facebook'
          '@controller': 'Authentication'
          '@action': 'authenticate'
          '@subpackage': NULL
        success_redirect_uri:
          '@package': 'Scoutrace.Scoutrace'
          '@controller': 'Standard'
          '@action': 'index'
          '@subpackage': NULL

TYPO3:
  Flow:
    security:
      authentication:
        providers:
          FacebookProvider:
            provider: Flowpack\Authentication\Facebook\Security\Authentication\Provider\FacebookProvider
            entryPoint: 'WebRedirect'
            entryPointOptions:
              routeValues:
                '@package': 'Flowpack.Authentication.Facebook'
                '@controller': 'Authentication'
                '@action': 'authenticate'
